default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 5432
development:
  <<: *default
  host: ec2-50-16-231-2.compute-1.amazonaws.com
  database: d5a1fr7p7ied8a
  username: wpfgcfqtoogznd
  password: 333504ce17359de328cebc67cd7d3d2e830906ebc12f50e1fa9b6a6c382be4c8